trigger:
- master
- release/*

phases:
- phase: Linux
  queue:
    name: Hosted Linux Preview
  variables:
    DOTNET_HOME: $(Agent.WorkFolder)/.dotnet
  steps:
  - checkout: self
    clean: true
  - script: ./build.sh -ci -bl:artifacts/logs/build.binlog -p:VSTestVerboseOutput=true -p:VSTestBlame=true 
    displayName: Run build.sh
    timeoutInMinutes: 9
  - script: "ps -ef"
    condition: always()
    displayName: List processes
